stages:
  - build
  - test
  - lint

variables:
  # When using dind, it's wise to use the overlayfs driver for
  # improved performance.
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"

# This service is used for building docker images
services:
  - docker:dind

build_api:
  stage: build
  image: docker:latest
  before_script:
    # Docker login is required to push images to the registry, but it's a good practice
    # to include it even for building, in case you want to push later.
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE/api:latest -f Dockerfile.dev.api .

build_www:
  stage: build
  image: docker:latest
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE/www:latest -f Dockerfile.dev.www .

test_api:
  stage: test
  image: $CI_REGISTRY_IMAGE/api:latest
  before_script:
    - pip install -r requirements.txt
  script:
    - python manage.py test

test_www:
  stage: test
  image: $CI_REGISTRY_IMAGE/www:latest
  before_script:
    - cd www
    - npm install
  script:
    - npm test

lint_api:
  stage: lint
  image: python:3.8-slim
  before_script:
    - pip install ruff
  script:
    - ruff check .

lint_www:
  stage: lint
  image: $CI_REGISTRY_IMAGE/www:latest
  before_script:
    - cd www
    - npm install
  script:
    - npm run lint
