stages:
  - build
  - test
  - lint
  - deploy

build_api:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t api:latest -f Dockerfile.dev.api .
    - docker save api:latest > api.tar
  artifacts:
    paths:
      - api.tar

build_www:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t www:latest -f Dockerfile.dev.www .
    - docker save www:latest > www.tar
  artifacts:
    paths:
      - www.tar

test_api:
  stage: test
  image: docker:latest
  services:
    - docker:dind
  variables:
    SECRET_KEY: 'a-secret-key'
    DATABASE_URL: sqlite:////tmp/db.sqlite3
    DEBUG: 'True'
  script:
    - docker load < api.tar
    - docker run -e SECRET_KEY="$SECRET_KEY" -e DATABASE_URL="$DATABASE_URL" -e DEBUG="$DEBUG" api:latest python manage.py test
  dependencies:
    - build_api

test_www:
  stage: test
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker load < www.tar
    - docker run www:latest npm test
  dependencies:
    - build_www

lint_api:
  stage: lint
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker load < api.tar
    - docker run api:latest flake8 app api --config /app/.flake8
  dependencies:
    - build_api

lint_www:
  stage: lint
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker load < www.tar
    - docker run --rm -w /app/www www:latest npm run lint
  dependencies:
    - build_www

variables:
  IMAGE_BACKEND: registry.gitlab.com/vcpvitor-group/vcpVitor-project/backend
  IMAGE_FRONTEND: registry.gitlab.com/vcpvitor-group/vcpVitor-project/frontend
  DOCKER_DRIVER: overlay2

.deploy_template: &deploy_template
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - echo "$CI_JOB_TOKEN" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY

deploy_backend:
  <<: *deploy_template
  script:
    - docker build -t $IMAGE_BACKEND -f Dockerfile.prod.api .
    - docker push $IMAGE_BACKEND
  only:
    - main

deploy_frontend:
  <<: *deploy_template
  script:
    - docker build -t $IMAGE_FRONTEND -f Dockerfile.prod.www .
    - docker push $IMAGE_FRONTEND
  only:
    - main