# Use the Python version specified in runtime.txt
FROM python:3.8-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set work directory
WORKDIR /app

# Install dependencies
# First copy only the requirements to leverage Docker cache

# Install system dependencies required by psycopg2
RUN apt-get update && apt-get install -y gcc libpq-dev

COPY ./requirements /app/requirements
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copy project
COPY . /app/
