# Etapa 1: Build
FROM node:18-slim AS builder

WORKDIR /app

COPY www/package*.json ./
COPY www/ ./

# ⚠️ Adiciona essa variável ANTES de buildar
ENV NODE_OPTIONS=--openssl-legacy-provider

RUN npm install --legacy-peer-deps
RUN npm run build

# Etapa 2: Execução com Next.js
FROM node:18-slim

WORKDIR /app
COPY --from=builder /app /app

# ⚠️ Adiciona também no ambiente final
ENV NODE_ENV=production
ENV NODE_OPTIONS=--openssl-legacy-provider

EXPOSE 3000

CMD ["npm", "run", "start"]
