version: '3.8'

services:
  www:
    build:
      context: .
      dockerfile: Dockerfile.prod.www
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_HOST=http://localhost:4001
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev.api  # ← se tiver um Dockerfile.prod.api, substitua aqui
    command: python manage.py runserver 0.0.0.0:4001
    volumes:
      - .:/app
    ports:
      - "4001:4001"
    env_file:
      - .env.prod
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=nextjs_django_prod
      - POSTGRES_USER=nextjs_django_prod
      - POSTGRES_PASSWORD=nextjs_django_prod

volumes:
  postgres_data:
